spring:
  application:
    name: buy-service

server:
  port: 8301


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
     defaultZone: http://localhost:8302/eureka/
  instance:
    hostname: localhost
#    securePort: ${server.port}
#    securePortEnabled: true
#    nonSecurePortEnabled: false


#keycloak:
#  auth-server-url: http://localhost:8080/auth
#  realm: CryptoCurrency
#  public-client: true
#  resource: login
#  security-constraints[0].authRoles[0]: user
#  security-constraints[0].securityCollections[0].patterns[0]: /buy-service/*

  #credentials:
   #     secret: 942227b3-54cb-458f-aa09-adc084e9da9c
